# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LuksoCli < Formula
  desc ""
  homepage "https://github.com/lukso-network/homebrew-tools"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.2/lukso-cli_0.0.2_darwin_arm64.tar.gz"
      sha256 "5ae9da09f4be276c1de95f912908ceb9a8e1ffcbde54fcabd0f5f259e5000b82"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.2/lukso-cli_0.0.2_darwin_amd64.tar.gz"
      sha256 "e2566cda884c4a7dada341bee6e146b9cc940d9b6c25ca76bbc078f4a41cc778"

      def install
        bin.install "lukso-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.2/lukso-cli_0.0.2_linux_arm64.tar.gz"
      sha256 "c6df6a0ff88bc907502443ad097abb387beef30cb664c683dad1240d36a186d6"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.2/lukso-cli_0.0.2_linux_amd64.tar.gz"
      sha256 "5cd2ba10cb69bdefaf24fdc6a8f1a2cc61a7eaba67f87986571e78f734e9437b"

      def install
        bin.install "lukso-cli"
      end
    end
  end
end
