# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lukso < Formula
  desc ""
  homepage "https://github.com/lukso-network/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "a2f41024d6b8b86a078ec2c1b56b1de4c32cea70254f41affee65443615a9759"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "e5895b188e74dbd70a4fd8ee2afcd9e7c7f6a0ff9e919e978c65ab594f4f43e0"

      def install
        bin.install "lukso-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "87285cc46015da2f01837eb074eef04d2228d12a0ec4e841765ed18fe30a26d0"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "5a1289012a2877b4034da026057bf3cbdb48c87761f367b3a0eb0e422dcef78b"

      def install
        bin.install "lukso-cli"
      end
    end
  end
end
